### ISSUE TITLE
How to check an item in an array when you don't know its index?

### ISSUE THREAD

**Issue by DannyRyman** [pwall567/json-kotlin-test#1]
Thanks for your work, we are finding the library very helpful for testing JSON.

We are using code similar to the below to avoid duplication in our tests:

```
private fun assertSingleItem(json: JsonString, tests: JSONExpect.() -> Unit) {
    JSONExpect.expectJSON(json) {
        property("activities") { 
            property("attributes") { // this is an array
                count(1)
                item(0, tests)
            }
        }
    }
}
```

The issue is that we now have a different use case whereby activities, instead of containing only a single item, can contain a number of items; however we should be able to single out an individual item based on some given criteria. In short what we would like to do is the equivalent of the `single` function available on kotlin lists (for example) to locate a single item based on a set of criteria.

**Comment by pwall567** [comment]
Hi, thanks for the feedback.

For cases where you want to perform tests that follow a common pattern in a number of places, I recommend using extension functions on `JSONExpect`, for example:
```kotlin

    fun JSONExpect.single(tests: JSONExpect.() -> Unit) {
        if (nodeAsArray.size != 1)
            error("not exactly one entry")
        item(0, tests)
    }
```
Then you can code your tests as:
```kotlin
        expectJSON("""["abc"]""") {
            single {
                value("abc")
            }
        }
```
Or to use `single` with a predicate (which is what I think you're talking about):
```kotlin

    fun JSONExpect.single(predicate: (Any?) -> Boolean, tests: JSONExpect.() -> Unit) {
        nodeAsArray.indexOfFirst(predicate).let { 
            when (it) {
                -1 -> error("not found")
                else -> item(it, tests)
            }
        }
    }
```
Then your tests might look something like:
```kotlin
        expectJSON("""["a","abc"]""") {
            single({ it is String && it.length == 3 }) {
                value("abc")
            }
        }
```
`nodeAsArray` and `error` are documented in [Custom Tests](https://github.com/pwall567/json-kotlin-test#custom-tests).

Does this help?

I'll look into adding a function like this to the library - the best enhancements are those resulting from actual uses.

**Comment by DannyRyman** [comment]
Thanks for coming back to me so quickly. I think I was close to getting a similar solution; however, I may have found a bug which prevented me from solving this myself. I will raise a separate issue as I feel this is moving away from the original question :)
