### ISSUE TITLE
Possible bug with nodeAsObject?

### ISSUE THREAD

**Issue by DannyRyman** [pwall567/json-kotlin-test#2]
Unless I am misunderstanding the API (which could very well be the case), I might have found a bug with the code thinking an object is an array. It is probably more easily explained through code:

```
class JsonExpectTests : ExpectSpec({
    context("given some json with an array of objects") {
        val json = """
            {
                "entries": [{
                  "id": "first"
                }, {
                  "id": "second"
                }]
            }
        """.trimIndent()

        @Suppress("UNCHECKED_CAST")
        expect("to be able to access object properties (working)") {
            JSONExpect.expectJSON(json) {
                property("entries") {
                    nodeAsArray.first().let {
                        val obj = it as Map<String, Any?>
                        obj["id"].shouldBe("first")
                    }
                }
            }
        }

        expect("to be able to access object properties (failing)") {
            JSONExpect.expectJSON(json) {
                property("entries") {
                    nodeAsArray.first().let {
                        // Fails with: JSON type doesn't match - Expected object, was array
                        nodeAsObject["id"].shouldBe("first")
                    }
                }
            }
        }
    }
})
```

I expected to be able to use the nodeAsObject to inspect the properties of an entry object (as per the second failing test), but it thinks it is an array. Interestingly casting this manually, as per the first test, appears to work.

Do you think this is a bug, or am I doing something stupid?

**Comment by pwall567** [comment]
Not stupidity, but not a bug either.  Perhaps an indicator of a need for more documentation.

`node` and `nodeAsXxxx` give access to the current context node.  The initial context is established by the `expectJSON()`, and then `property(name) { ... }` and `item(index) { ... }` establish a new context in which the child tests are executed.  Neither `.first()` or `.let` establish a new context, so the `nodeAsObject` in your failing example is executed in the outer context, in which `node` is an array.

The answer is this case is to use `item(0) { ... }` but I'm guessing you know that and the example here is a simplification of the problem you're trying to solve (maintainers love simplified examples that isolate the issue at hand, but I think in this case you may have simplified away the underlying issue).

If you wish to apply tests to an item in an array, where the index of that item may vary, the answer is to use something like:
```kotlin
            expectJSON(json) {
                property("entries") {
                    val index = calculateIndex()
                    item(index) {
                        // tests on the selected item (new context, where "node" is the selected item)
                    }
                }
            }
```
Does this address your issue?

BTW, I notice that you're writing `JSONExpect.expectJSON(json) {` - I generally encourage people to add the import:
```kotlin
import net.pwall.json.test.JSONExpect.Companion.expectJSON
```
and then you can just use `expectJSON(json) {`.  But it's your call.

**Comment by DannyRyman** [comment]
Makes perfect sense. Thanks for the clarification.
